# RECORD_SCREEN_DESTINATION="$HOME/.cache/irdaislakhuafa_$(date '+%d_%B_%Y-%H.%M.%S').mp4"
RECORD_SCREEN_DESTINATION="/tmp/$(date '+%d_%B_%Y-%H.%M.%S').mp4"
NOTIFICATION_EXPIRE_TIME_IN_MILISEC=2000
SCREEN_RECORDER_APP_NAME="WF Recorder"
UNMOUNT_APP_NAME="umount.sh"
